version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secretPassword
      POSTGRES_DB: vss
    ports:
      - "5432:5432"
    volumes:
      - "./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
  api:
    image: gschwind/shoppinglistapi
    environment: 
      ConnectionString: "Server=localhost;Port=5432;Database=vss;User Id=postgres;Password=secretPassword;"
    ports:
      - "5001:5001"
      - "44370:44370"