version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secretPassword
      POSTGRES_DB: vss
    ports:
      - "5454:5454"
    volumes:
      - "./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql"